<a href="https://colab.research.google.com/github/bcury/Machine-Learning-Projects/blob/main/ML_CLASSIFICA%C3%87%C3%83O_TEXTOS_SENTIMENTOS_NLP_tweet_Flask!!.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


In [3]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split

In [4]:
base = pd.read_csv('/content/twitter-sentiments.csv')

In [5]:
base.head()

id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [6]:
base.shape

(31962, 3)

In [7]:
base.label.value_counts()

0    29720
1     2242
Name: label, dtype: int64

In [9]:
treino, teste = train_test_split(base, test_size = 0.2, stratify = base['label'], random_state=1)

In [10]:
treino.shape, teste.shape

((25569, 3), (6393, 3))

In [11]:
treino.label.value_counts(normalize=True)

0    0.929837
1    0.070163
Name: label, dtype: float64

In [12]:
teste.label.value_counts(normalize=True)

0    0.929923
1    0.070077
Name: label, dtype: float64

In [13]:
tfidf_vectorizer = TfidfVectorizer(lowercase= True, max_features=1000, stop_words=ENGLISH_STOP_WORDS)

In [15]:
tfidf_vectorizer.fit(treino.tweet)

TfidfVectorizer(max_features=1000,
                stop_words=frozenset({'a', 'about', 'above', 'across', 'after',
                                      'afterwards', 'again', 'against', 'all',
                                      'almost', 'alone', 'along', 'already',
                                      'also', 'although', 'always', 'am',
                                      'among', 'amongst', 'amoungst', 'amount',
                                      'an', 'and', 'another', 'any', 'anyhow',
                                      'anyone', 'anything', 'anyway',
                                      'anywhere', ...}))

In [16]:
treino_idf = tfidf_vectorizer.transform(treino.tweet)
teste_idf  = tfidf_vectorizer.transform(teste.tweet)

- regressao logistica

In [17]:
regressao = LogisticRegression()

In [18]:
regressao.fit(treino_idf, treino.label)

LogisticRegression()

In [21]:
previsao_treino = regressao.predict(treino_idf)

In [22]:
previsao_treino

array([0, 0, 0, ..., 0, 0, 0])

In [23]:
previsao_teste = regressao.predict(teste_idf)

In [24]:
previsao_teste

array([0, 0, 0, ..., 0, 0, 0])

In [25]:
#f1 score

In [28]:
f1_score(y_true=treino.label, y_pred=previsao_treino)

0.49162011173184356

In [29]:
f1_score(y_true=teste.label, y_pred= previsao_teste)

0.4692556634304207

- pipeline

In [30]:
pipeline = Pipeline(steps= [('tfidf', TfidfVectorizer(lowercase=True,
                                                      max_features=1000,
                                                      stop_words= ENGLISH_STOP_WORDS)),
                            ('model', LogisticRegression())])

In [31]:
pipeline.fit(treino.tweet, treino.label)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_features=1000,
                                 stop_words=frozenset({'a', 'about', 'above',
                                                       'across', 'after',
                                                       'afterwards', 'again',
                                                       'against', 'all',
                                                       'almost', 'alone',
                                                       'along', 'already',
                                                       'also', 'although',
                                                       'always', 'am', 'among',
                                                       'amongst', 'amoungst',
                                                       'amount', 'an', 'and',
                                                       'another', 'any',
                                                       'anyhow', 'anyone',
           

In [32]:
pipeline.predict(treino.tweet)

array([0, 0, 0, ..., 0, 0, 0])

In [33]:
text = ["Virat Kohli, AB de Villiers set to auction their 'Green Day' kits from 2016 IPL match to raise funds"]

In [34]:
pipeline.predict(text)

array([0])

In [35]:
from joblib import dump

In [36]:
dump(pipeline, filename="text_classification.joblib")

['text_classification.joblib']

In [37]:
base[base.label == 1]

id  label                                              tweet
13        14      1  @user #cnn calls #michigan middle school 'buil...
14        15      1  no comment!  in #australia   #opkillingbay #se...
17        18      1                             retweet if you agree! 
23        24      1    @user @user lumpy says i am a . prove it lumpy.
34        35      1  it's unbelievable that in the 21st century we'...
...      ...    ...                                                ...
31934  31935      1  lady banned from kentucky mall. @user  #jcpenn...
31946  31947      1  @user omfg i'm offended! i'm a  mailbox and i'...
31947  31948      1  @user @user you don't have the balls to hashta...
31948  31949      1   makes you ask yourself, who am i? then am i a...
31960  31961      1  @user #sikh #temple vandalised in in #calgary,...

[2242 rows x 3 columns]

In [45]:
import tweepy
import time


In [40]:
pd.set_option('display.max_colwidth', 1000)

In [41]:
# api key
api_key = "Enter API Key"
# api secret key
api_secret_key = "Enter API Secret Key"
# access token
access_token = "Enter Access Token"
# access token secret
access_token_secret = "Enter Access Token Secret"


In [42]:
authentication = tweepy.OAuthHandler(api_key, api_secret_key)
authentication.set_access_token(access_token, access_token_secret)
api = tweepy.API(authentication, wait_on_rate_limit=True)

In [43]:
def get_related_tweets(text_query):
    # list to store tweets
    tweets_list = []
    # no of tweets
    count = 50
    try:
        # Pulling individual tweets from query
        for tweet in api.search(q=text_query, count=count):
            print(tweet.text)
            # Adding to list that contains all tweets
            tweets_list.append({'created_at': tweet.created_at,
                                'tweet_id': tweet.id,
                                'tweet_text': tweet.text})
        return pd.DataFrame.from_dict(tweets_list)

    except BaseException as e:
        print('failed on_status,', str(e))
        time.sleep(3)

In [ ]:
from flask import Flask, render_template, request, redirect, url_for
from joblib import load


pipeline = load("text_classification.joblib")


def requestResults(name):
    tweets = get_related_tweets(name)
    tweets['prediction'] = pipeline.predict(tweets['tweet_text'])
    data = str(tweets.prediction.value_counts()) + '\n\n'
    return data + str(tweets)


app = Flask(__name__)


@app.route('/')
def home():
    return render_template('home.html')


@app.route('/', methods=['POST', 'GET'])
def get_data():
    if request.method == 'POST':
        user = request.form['search']
        return redirect(url_for('success', name=user))


@app.route('/success/<name>')
def success(name):
    return "<xmp>" + str(requestResults(name)) + " </xmp> "


if __name__ == '__main__' :
    app.run(debug=True)