<a href="https://colab.research.google.com/github/bcury/Machine-Learning-Projects/blob/main/ML_Modelagem_Matam%C3%A1tica_Sistemas_Lineares_Cramer%2C_Gauss%2C_minQuad%2CregressaoLinear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pandas as pd
import numpy as np
import scipy as sp
from scipy import linalg

**Sistema Linear**

x + 2y + 3z = 2;
2x -y + z = -1;
-2x -3y + 3z = -11

- Regra de Cramer

In [4]:
matriz = np.array([[1,2,3],
                  [2,-1,1],
                  [-2,-3,3]])
matriz

array([[ 1,  2,  3],
       [ 2, -1,  1],
       [-2, -3,  3]])

In [8]:
vetor = np.array([2,-1,-11]) #constantes de um sistema 
vetor

array([  2,  -1, -11])

In [6]:
matriz.shape

(3, 3)

In [7]:
vetor.shape

(3,)

Função regra de cramer para sistema com 3 incógnitas

In [9]:
matriz

array([[ 1,  2,  3],
       [ 2, -1,  1],
       [-2, -3,  3]])

In [11]:
np.array([matriz[:,0],matriz[:,1],matriz[:,2]]) #assim invertemos coluna com linha

array([[ 1,  2, -2],
       [ 2, -1, -3],
       [ 3,  1,  3]])

In [13]:
np.array([matriz[:,0],matriz[:,1],matriz[:,2]]).T # agora voltamos ela ao normal, usando a transposta

array([[ 1,  2,  3],
       [ 2, -1,  1],
       [-2, -3,  3]])

In [16]:
def cramer3 (A,v):
  determinante = sp.linalg.det(np.array([A[:,0],A[:,1],A[:,2]]).T)
  if determinante !=0:
    detx = sp.linalg.det(np.array([v[:],A[:,1],A[:,2]]).T)
    dety = sp.linalg.det(np.array([A[:,0],v[:],A[:,2]]).T)
    detz = sp.linalg.det(np.array([A[:,0],A[:,1],v[:]]).T)
    x = detx/determinante
    y = dety/determinante
    z = detz/determinante
    print(x)
    print(y)
    print(z)
  else:
    print('coef nulo')

In [17]:
cramer3(matriz, vetor)

1.0
2.0
-1.0


- estimativa por minimo quadrado

In [22]:
nota = pd.read_excel('/content/concurso.xlsx')

In [23]:
nota.shape

(25, 3)

In [25]:
nota.head(25)

inicio_estudo  tempo_estudo_dia  nota
0               5               120   8.1
1              13                90   6.8
2              20               120   7.0
3              28                60   7.4
4              20               150   9.3
5              24               150   7.5
6              18                60   7.6
7               8               120   8.0
8               2               240   7.0
9              12                90   7.3
10             15                90   8.6
11              9               120   8.3
12              6               180   7.9
13              4                90   6.4
14              8               150   7.8
15             12               120   9.4
16             10               180   8.8
17              3                90   6.9
18             15               180   7.7
19              9                90   8.2
20             24               120   8.6
21              5               150   8.1
22              7               120   7.2
23             12               180   8.5
24              2                90   6.1

In [26]:
nota.dtypes

inicio_estudo         int64
tempo_estudo_dia      int64
nota                float64
dtype: object

criação da matriz dos coeficientes

In [27]:
A = nota.drop(columns=['nota'])
A.head()

inicio_estudo  tempo_estudo_dia
0              5               120
1             13                90
2             20               120
3             28                60
4             20               150

In [28]:
type(A)

pandas.core.frame.DataFrame

In [29]:
A = A.values

In [30]:
print(A)

[[  5 120]
 [ 13  90]
 [ 20 120]
 [ 28  60]
 [ 20 150]
 [ 24 150]
 [ 18  60]
 [  8 120]
 [  2 240]
 [ 12  90]
 [ 15  90]
 [  9 120]
 [  6 180]
 [  4  90]
 [  8 150]
 [ 12 120]
 [ 10 180]
 [  3  90]
 [ 15 180]
 [  9  90]
 [ 24 120]
 [  5 150]
 [  7 120]
 [ 12 180]
 [  2  90]]


criação da matriz ds constantes

In [33]:
b = nota.drop(columns=['inicio_estudo','tempo_estudo_dia'])
b

nota
0    8.1
1    6.8
2    7.0
3    7.4
4    9.3
5    7.5
6    7.6
7    8.0
8    7.0
9    7.3
10   8.6
11   8.3
12   7.9
13   6.4
14   7.8
15   9.4
16   8.8
17   6.9
18   7.7
19   8.2
20   8.6
21   8.1
22   7.2
23   8.5
24   6.1

In [34]:
b = b.values
print(b)

[[8.1]
 [6.8]
 [7. ]
 [7.4]
 [9.3]
 [7.5]
 [7.6]
 [8. ]
 [7. ]
 [7.3]
 [8.6]
 [8.3]
 [7.9]
 [6.4]
 [7.8]
 [9.4]
 [8.8]
 [6.9]
 [7.7]
 [8.2]
 [8.6]
 [8.1]
 [7.2]
 [8.5]
 [6.1]]


In [35]:
#estimativa min quadrados



In [36]:
At = np.array(A).T
At

array([[  5,  13,  20,  28,  20,  24,  18,   8,   2,  12,  15,   9,   6,
          4,   8,  12,  10,   3,  15,   9,  24,   5,   7,  12,   2],
       [120,  90, 120,  60, 150, 150,  60, 120, 240,  90,  90, 120, 180,
         90, 150, 120, 180,  90, 180,  90, 120, 150, 120, 180,  90]])

In [37]:
#mult da At pela A
AtA = np.dot(At,A)
AtA

array([[  4669,  34950],
       [ 34950, 441900]])

In [38]:
#inversa da AtA
inversa = np.linalg.inv(AtA)
inversa


array([[ 5.24991072e-04, -4.15216971e-05],
       [-4.15216971e-05,  5.54691857e-06]])

In [39]:
Atb = np.dot(At, b)
Atb

array([[ 2305.9],
       [24726. ]])

In [41]:
x = np.dot(inversa, Atb)
x

array([[0.18391143],
       [0.04140823]])

ou

In [43]:
x = np.dot(np.dot(np.linalg.inv(np.dot(At,A)),At),b)
x

array([[0.18391143],
       [0.04140823]])

x e y

nota = 0.1839.incio_estudo + 0.0414.tempo_estudo_dia

In [44]:
resultado = nota
resultado

inicio_estudo  tempo_estudo_dia  nota
0               5               120   8.1
1              13                90   6.8
2              20               120   7.0
3              28                60   7.4
4              20               150   9.3
5              24               150   7.5
6              18                60   7.6
7               8               120   8.0
8               2               240   7.0
9              12                90   7.3
10             15                90   8.6
11              9               120   8.3
12              6               180   7.9
13              4                90   6.4
14              8               150   7.8
15             12               120   9.4
16             10               180   8.8
17              3                90   6.9
18             15               180   7.7
19              9                90   8.2
20             24               120   8.6
21              5               150   8.1
22              7               120   7.2
23             12               180   8.5
24              2                90   6.1

In [45]:
resultado['previsao'] = resultado['inicio_estudo']*x[0] + resultado['tempo_estudo_dia']*x[1]
resultado

inicio_estudo  tempo_estudo_dia  nota   previsao
0               5               120   8.1   5.888544
1              13                90   6.8   6.117589
2              20               120   7.0   8.647216
3              28                60   7.4   7.634014
4              20               150   9.3   9.889463
5              24               150   7.5  10.625108
6              18                60   7.6   5.794899
7               8               120   8.0   6.440279
8               2               240   7.0  10.305797
9              12                90   7.3   5.933678
10             15                90   8.6   6.485412
11              9               120   8.3   6.624190
12              6               180   7.9   8.556949
13              4                90   6.4   4.462386
14              8               150   7.8   7.682525
15             12               120   9.4   7.175924
16             10               180   8.8   9.292595
17              3                90   6.9   4.278475
18             15               180   7.7  10.212152
19              9                90   8.2   5.381943
20             24               120   8.6   9.382862
21              5               150   8.1   7.130791
22              7               120   7.2   6.256367
23             12               180   8.5   9.660418
24              2                90   6.1   4.094563

erro médio absoluto

In [46]:
from sklearn.metrics import mean_absolute_error

In [47]:
mean_absolute_error(resultado.nota, resultado.previsao)

1.5823602999826787

In [49]:
resultado['erro_abs'] = abs(resultado.nota - resultado.previsao)

In [50]:
resultado

inicio_estudo  tempo_estudo_dia  nota   previsao  erro_abs
0               5               120   8.1   5.888544  2.211456
1              13                90   6.8   6.117589  0.682411
2              20               120   7.0   8.647216  1.647216
3              28                60   7.4   7.634014  0.234014
4              20               150   9.3   9.889463  0.589463
5              24               150   7.5  10.625108  3.125108
6              18                60   7.6   5.794899  1.805101
7               8               120   8.0   6.440279  1.559721
8               2               240   7.0  10.305797  3.305797
9              12                90   7.3   5.933678  1.366322
10             15                90   8.6   6.485412  2.114588
11              9               120   8.3   6.624190  1.675810
12              6               180   7.9   8.556949  0.656949
13              4                90   6.4   4.462386  1.937614
14              8               150   7.8   7.682525  0.117475
15             12               120   9.4   7.175924  2.224076
16             10               180   8.8   9.292595  0.492595
17              3                90   6.9   4.278475  2.621525
18             15               180   7.7  10.212152  2.512152
19              9                90   8.2   5.381943  2.818057
20             24               120   8.6   9.382862  0.782862
21              5               150   8.1   7.130791  0.969209
22              7               120   7.2   6.256367  0.943633
23             12               180   8.5   9.660418  1.160418
24              2                90   6.1   4.094563  2.005437

**Criação de um modelo de Regressao Linear Multipla**

In [51]:
resultado.head()

inicio_estudo  tempo_estudo_dia  nota  previsao  erro_abs
0              5               120   8.1  5.888544  2.211456
1             13                90   6.8  6.117589  0.682411
2             20               120   7.0  8.647216  1.647216
3             28                60   7.4  7.634014  0.234014
4             20               150   9.3  9.889463  0.589463

In [52]:
B = resultado.drop(columns=['nota','previsao','erro_abs'])
B

inicio_estudo  tempo_estudo_dia
0               5               120
1              13                90
2              20               120
3              28                60
4              20               150
5              24               150
6              18                60
7               8               120
8               2               240
9              12                90
10             15                90
11              9               120
12              6               180
13              4                90
14              8               150
15             12               120
16             10               180
17              3                90
18             15               180
19              9                90
20             24               120
21              5               150
22              7               120
23             12               180
24              2                90

In [53]:
B = B.assign(unidade=1)

In [54]:
B

inicio_estudo  tempo_estudo_dia  unidade
0               5               120        1
1              13                90        1
2              20               120        1
3              28                60        1
4              20               150        1
5              24               150        1
6              18                60        1
7               8               120        1
8               2               240        1
9              12                90        1
10             15                90        1
11              9               120        1
12              6               180        1
13              4                90        1
14              8               150        1
15             12               120        1
16             10               180        1
17              3                90        1
18             15               180        1
19              9                90        1
20             24               120        1
21              5               150        1
22              7               120        1
23             12               180        1
24              2                90        1

In [55]:
B = B[['unidade','inicio_estudo','tempo_estudo_dia']]

In [56]:
B

unidade  inicio_estudo  tempo_estudo_dia
0         1              5               120
1         1             13                90
2         1             20               120
3         1             28                60
4         1             20               150
5         1             24               150
6         1             18                60
7         1              8               120
8         1              2               240
9         1             12                90
10        1             15                90
11        1              9               120
12        1              6               180
13        1              4                90
14        1              8               150
15        1             12               120
16        1             10               180
17        1              3                90
18        1             15               180
19        1              9                90
20        1             24               120
21        1              5               150
22        1              7               120
23        1             12               180
24        1              2                90

In [57]:
Bt = np.array(B).T

In [58]:
Bt

array([[  1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1],
       [  5,  13,  20,  28,  20,  24,  18,   8,   2,  12,  15,   9,   6,
          4,   8,  12,  10,   3,  15,   9,  24,   5,   7,  12,   2],
       [120,  90, 120,  60, 150, 150,  60, 120, 240,  90,  90, 120, 180,
         90, 150, 120, 180,  90, 180,  90, 120, 150, 120, 180,  90]])

In [60]:
x2 = np.dot(np.dot(np.linalg.inv(np.dot(Bt,B)),Bt),b)
x2

array([[6.48712882e+00],
       [4.13304622e-02],
       [6.44273496e-03]])

nota = 6.4871 + 0.0413.inicio_estudo  + 0.00644.tempo_estudo_dia

In [62]:
resultado['previsao2'] = x2[0] + resultado['inicio_estudo']*x2[1] + resultado['tempo_estudo_dia']*x2[2]

In [63]:
resultado

inicio_estudo  tempo_estudo_dia  nota   previsao  erro_abs  previsao2
0               5               120   8.1   5.888544  2.211456   7.466909
1              13                90   6.8   6.117589  0.682411   7.604271
2              20               120   7.0   8.647216  1.647216   8.086866
3              28                60   7.4   7.634014  0.234014   8.030946
4              20               150   9.3   9.889463  0.589463   8.280148
5              24               150   7.5  10.625108  3.125108   8.445470
6              18                60   7.6   5.794899  1.805101   7.617641
7               8               120   8.0   6.440279  1.559721   7.590901
8               2               240   7.0  10.305797  3.305797   8.116046
9              12                90   7.3   5.933678  1.366322   7.562941
10             15                90   8.6   6.485412  2.114588   7.686932
11              9               120   8.3   6.624190  1.675810   7.632231
12              6               180   7.9   8.556949  0.656949   7.894804
13              4                90   6.4   4.462386  1.937614   7.232297
14              8               150   7.8   7.682525  0.117475   7.784183
15             12               120   9.4   7.175924  2.224076   7.756223
16             10               180   8.8   9.292595  0.492595   8.060126
17              3                90   6.9   4.278475  2.621525   7.190966
18             15               180   7.7  10.212152  2.512152   8.266778
19              9                90   8.2   5.381943  2.818057   7.438949
20             24               120   8.6   9.382862  0.782862   8.252188
21              5               150   8.1   7.130791  0.969209   7.660191
22              7               120   7.2   6.256367  0.943633   7.549570
23             12               180   8.5   9.660418  1.160418   8.142787
24              2                90   6.1   4.094563  2.005437   7.149636

In [64]:
mean_absolute_error(resultado.nota, resultado.previsao2)

0.6362742744691536

In [65]:
resultado['erro_abs2'] = abs(resultado.nota - resultado.previsao2)

In [66]:
resultado

inicio_estudo  tempo_estudo_dia  nota  ...  erro_abs  previsao2  erro_abs2
0               5               120   8.1  ...  2.211456   7.466909   0.633091
1              13                90   6.8  ...  0.682411   7.604271   0.804271
2              20               120   7.0  ...  1.647216   8.086866   1.086866
3              28                60   7.4  ...  0.234014   8.030946   0.630946
4              20               150   9.3  ...  0.589463   8.280148   1.019852
5              24               150   7.5  ...  3.125108   8.445470   0.945470
6              18                60   7.6  ...  1.805101   7.617641   0.017641
7               8               120   8.0  ...  1.559721   7.590901   0.409099
8               2               240   7.0  ...  3.305797   8.116046   1.116046
9              12                90   7.3  ...  1.366322   7.562941   0.262941
10             15                90   8.6  ...  2.114588   7.686932   0.913068
11              9               120   8.3  ...  1.675810   7.632231   0.667769
12              6               180   7.9  ...  0.656949   7.894804   0.005196
13              4                90   6.4  ...  1.937614   7.232297   0.832297
14              8               150   7.8  ...  0.117475   7.784183   0.015817
15             12               120   9.4  ...  2.224076   7.756223   1.643777
16             10               180   8.8  ...  0.492595   8.060126   0.739874
17              3                90   6.9  ...  2.621525   7.190966   0.290966
18             15               180   7.7  ...  2.512152   8.266778   0.566778
19              9                90   8.2  ...  2.818057   7.438949   0.761051
20             24               120   8.6  ...  0.782862   8.252188   0.347812
21              5               150   8.1  ...  0.969209   7.660191   0.439809
22              7               120   7.2  ...  0.943633   7.549570   0.349570
23             12               180   8.5  ...  1.160418   8.142787   0.357213
24              2                90   6.1  ...  2.005437   7.149636   1.049636

[25 rows x 7 columns]

ou então

In [67]:
import statsmodels.formula.api as smf

In [68]:
import statsmodels.stats.api as sms

In [69]:
modelo = smf.ols('nota ~ inicio_estudo + tempo_estudo_dia', data=nota).fit()

In [71]:
print(modelo.summary())

                            OLS Regression Results                            
Dep. Variable:                   nota   R-squared:                       0.184
Model:                            OLS   Adj. R-squared:                  0.110
Method:                 Least Squares   F-statistic:                     2.485
Date:                Mon, 21 Feb 2022   Prob (F-statistic):              0.106
Time:                        20:59:54   Log-Likelihood:                -28.151
No. Observations:                  25   AIC:                             62.30
Df Residuals:                      22   BIC:                             65.96
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            6.4871      0.624  