<a href="https://colab.research.google.com/github/bcury/Machine-Learning-Projects/blob/main/ML_regression_forecast_predictWeather_DecisionTree_RandomForest_LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime

In [2]:
base = pd.read_csv('/content/GlobalTemperatures.csv')

In [3]:
base.shape

(3192, 9)

In [4]:
base.head()

dt  ...  LandAndOceanAverageTemperatureUncertainty
0  1750-01-01  ...                                        NaN
1  1750-02-01  ...                                        NaN
2  1750-03-01  ...                                        NaN
3  1750-04-01  ...                                        NaN
4  1750-05-01  ...                                        NaN

[5 rows x 9 columns]

In [5]:
base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3192 entries, 0 to 3191
Data columns (total 9 columns):
 #   Column                                     Non-Null Count  Dtype  
---  ------                                     --------------  -----  
 0   dt                                         3192 non-null   object 
 1   LandAverageTemperature                     3180 non-null   float64
 2   LandAverageTemperatureUncertainty          3180 non-null   float64
 3   LandMaxTemperature                         1992 non-null   float64
 4   LandMaxTemperatureUncertainty              1992 non-null   float64
 5   LandMinTemperature                         1992 non-null   float64
 6   LandMinTemperatureUncertainty              1992 non-null   float64
 7   LandAndOceanAverageTemperature             1992 non-null   float64
 8   LandAndOceanAverageTemperatureUncertainty  1992 non-null   float64
dtypes: float64(8), object(1)
memory usage: 224.6+ KB


In [6]:
base.isnull().sum()

dt                                              0
LandAverageTemperature                         12
LandAverageTemperatureUncertainty              12
LandMaxTemperature                           1200
LandMaxTemperatureUncertainty                1200
LandMinTemperature                           1200
LandMinTemperatureUncertainty                1200
LandAndOceanAverageTemperature               1200
LandAndOceanAverageTemperatureUncertainty    1200
dtype: int64

In [19]:
np.unique(base['LandAndOceanAverageTemperature'], return_counts=True)

(array([12.475, 12.62 , 12.658, ...,    nan,    nan,    nan]),
 array([1, 1, 1, ..., 1, 1, 1]))

In [20]:
base.loc[pd.isnull(base['LandAndOceanAverageTemperature'])]

dt  ...  LandAndOceanAverageTemperatureUncertainty
0     1750-01-01  ...                                        NaN
1     1750-02-01  ...                                        NaN
2     1750-03-01  ...                                        NaN
3     1750-04-01  ...                                        NaN
4     1750-05-01  ...                                        NaN
...          ...  ...                                        ...
1195  1849-08-01  ...                                        NaN
1196  1849-09-01  ...                                        NaN
1197  1849-10-01  ...                                        NaN
1198  1849-11-01  ...                                        NaN
1199  1849-12-01  ...                                        NaN

[1200 rows x 9 columns]

In [21]:
base.loc[pd.isnull(base['LandAndOceanAverageTemperature'])]

dt  ...  LandAndOceanAverageTemperatureUncertainty
0     1750-01-01  ...                                        NaN
1     1750-02-01  ...                                        NaN
2     1750-03-01  ...                                        NaN
3     1750-04-01  ...                                        NaN
4     1750-05-01  ...                                        NaN
...          ...  ...                                        ...
1195  1849-08-01  ...                                        NaN
1196  1849-09-01  ...                                        NaN
1197  1849-10-01  ...                                        NaN
1198  1849-11-01  ...                                        NaN
1199  1849-12-01  ...                                        NaN

[1200 rows x 9 columns]

In [22]:
base['LandAndOceanAverageTemperature'].fillna(base['LandAndOceanAverageTemperature'].mean(), inplace = True)

In [23]:
base.head()

dt  ...  LandAndOceanAverageTemperatureUncertainty
0  1750-01-01  ...                                        NaN
1  1750-02-01  ...                                        NaN
2  1750-03-01  ...                                        NaN
3  1750-04-01  ...                                        NaN
4  1750-05-01  ...                                        NaN

[5 rows x 9 columns]

In [24]:
base['LandMaxTemperature'].fillna(base['LandMaxTemperature'].mean(), inplace = True)

In [25]:
base.head()

dt  ...  LandAndOceanAverageTemperatureUncertainty
0  1750-01-01  ...                                        NaN
1  1750-02-01  ...                                        NaN
2  1750-03-01  ...                                        NaN
3  1750-04-01  ...                                        NaN
4  1750-05-01  ...                                        NaN

[5 rows x 9 columns]

In [27]:
base['LandMaxTemperatureUncertainty'].fillna(base['LandMaxTemperatureUncertainty'].mean(), inplace = True)

In [28]:
base['LandMinTemperature'].fillna(base['LandMinTemperature'].mean(), inplace = True)

In [29]:
base['LandMinTemperatureUncertainty'].fillna(base['LandMinTemperatureUncertainty'].mean(), inplace = True)

In [30]:
base.head()

dt  ...  LandAndOceanAverageTemperatureUncertainty
0  1750-01-01  ...                                        NaN
1  1750-02-01  ...                                        NaN
2  1750-03-01  ...                                        NaN
3  1750-04-01  ...                                        NaN
4  1750-05-01  ...                                        NaN

[5 rows x 9 columns]

In [31]:
base['LandAndOceanAverageTemperatureUncertainty'].fillna(base['LandAndOceanAverageTemperatureUncertainty'].mean(), inplace = True)

In [32]:
base.head()

dt  ...  LandAndOceanAverageTemperatureUncertainty
0  1750-01-01  ...                                   0.128532
1  1750-02-01  ...                                   0.128532
2  1750-03-01  ...                                   0.128532
3  1750-04-01  ...                                   0.128532
4  1750-05-01  ...                                   0.128532

[5 rows x 9 columns]

In [35]:
base['LandAverageTemperatureUncertainty'].fillna(base['LandAverageTemperatureUncertainty'].mean(), inplace = True)

In [37]:
base['LandAverageTemperature'].fillna(base['LandAverageTemperature'].mean(), inplace = True)

pronto, valores nulos preenchidos com a média

In [38]:
base.isnull().sum()

dt                                           0
LandAverageTemperature                       0
LandAverageTemperatureUncertainty            0
LandMaxTemperature                           0
LandMaxTemperatureUncertainty                0
LandMinTemperature                           0
LandMinTemperatureUncertainty                0
LandAndOceanAverageTemperature               0
LandAndOceanAverageTemperatureUncertainty    0
dtype: int64

In [39]:
base.shape

(3192, 9)

In [40]:
base.head()

dt  ...  LandAndOceanAverageTemperatureUncertainty
0  1750-01-01  ...                                   0.128532
1  1750-02-01  ...                                   0.128532
2  1750-03-01  ...                                   0.128532
3  1750-04-01  ...                                   0.128532
4  1750-05-01  ...                                   0.128532

[5 rows x 9 columns]

In [41]:
base.tail()

dt  ...  LandAndOceanAverageTemperatureUncertainty
3187  2015-08-01  ...                                      0.057
3188  2015-09-01  ...                                      0.058
3189  2015-10-01  ...                                      0.062
3190  2015-11-01  ...                                      0.063
3191  2015-12-01  ...                                      0.062

[5 rows x 9 columns]

In [62]:
base['dt'] = pd.to_datetime(base.dt, format='%Y-%d-%m')

**Treinando o modelo**

In [75]:
x = base.iloc[:,[1,2,3,4,5,6,8]].values
y = base.iloc[:,7].values

In [76]:
x.shape

(3192, 7)

In [77]:
y.shape

(3192,)

In [78]:
from sklearn.model_selection import train_test_split

In [79]:
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size=0.25, random_state=0)

In [80]:
x_treino.shape

(2394, 7)

In [81]:
y_treino.shape

(2394,)

In [82]:
x_teste.shape

(798, 7)

In [83]:
y_teste.shape

(798,)

**Decision Tree**

In [84]:
from sklearn.tree import DecisionTreeRegressor

In [85]:
tree = DecisionTreeRegressor(criterion='mse')

In [86]:
tree.fit(x_treino, y_treino)

/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py:363: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,


DecisionTreeRegressor(criterion='mse')

In [87]:
previsao = tree.predict(x_teste)

In [88]:
previsao

array([15.21256576, 15.719     , 15.21256576, 15.21256576, 15.21256576,
       14.054     , 16.792     , 15.21256576, 15.21256576, 16.704     ,
       15.21256576, 14.609     , 15.21256576, 15.93      , 16.753     ,
       14.331     , 15.493     , 15.372     , 15.21256576, 15.21256576,
       17.607     , 15.21256576, 15.21256576, 15.21256576, 15.21256576,
       15.21256576, 16.543     , 13.936     , 15.21256576, 13.129     ,
       15.285     , 13.467     , 16.591     , 15.21256576, 15.21256576,
       15.254     , 15.936     , 16.613     , 13.364     , 16.304     ,
       16.152     , 13.264     , 13.506     , 15.21256576, 15.21256576,
       15.21256576, 15.21256576, 15.228     , 15.21256576, 15.808     ,
       15.21256576, 14.902     , 14.157     , 13.777     , 13.417     ,
       15.735     , 14.873     , 16.552     , 15.21256576, 15.21256576,
       14.299     , 15.21256576, 15.21256576, 16.444     , 15.21256576,
       15.21256576, 13.852     , 15.21256576, 15.21256576, 15.21

In [89]:
y_teste

array([15.21256576, 15.656     , 15.21256576, 15.21256576, 15.21256576,
       13.933     , 16.273     , 15.21256576, 15.21256576, 16.796     ,
       15.21256576, 14.516     , 15.21256576, 15.62      , 16.725     ,
       14.453     , 15.455     , 15.27      , 15.21256576, 15.21256576,
       17.423     , 15.21256576, 15.21256576, 15.21256576, 15.21256576,
       15.21256576, 16.716     , 13.81      , 15.21256576, 13.206     ,
       15.181     , 13.321     , 16.49      , 15.21256576, 15.21256576,
       15.19      , 15.641     , 16.553     , 13.344     , 16.45      ,
       16.212     , 13.555     , 13.529     , 15.21256576, 15.21256576,
       15.21256576, 15.21256576, 15.065     , 15.21256576, 15.962     ,
       15.21256576, 14.918     , 14.061     , 13.526     , 13.176     ,
       15.819     , 14.982     , 16.582     , 15.21256576, 15.21256576,
       14.418     , 15.21256576, 15.21256576, 16.309     , 15.21256576,
       15.21256576, 13.928     , 15.21256576, 15.21256576, 15.21

In [90]:
tree.score(x_treino, y_treino)

1.0

In [91]:
tree.score(x_teste,y_teste)

0.9829403355516639

excelente acurácia

- agora podemos prever alguns valores futuros

In [94]:
#tree.predict(np.array([[(1),(2),(3).(4),(5),(6),(8)]]))

In [95]:
tree.predict(np.array([[13000,0.080,17345,0.089,8000,0.233,0.060]])) # o resultado é nosso target(7) 'LandAndOceanAverageTemperature'

array([17.487])

In [98]:
tree.predict(np.array([[0,0.020,10345,0.060,8000,0.203,0.080]]))

array([16.757])

In [99]:
tree.predict(np.array([[2000,0.080,17345,0.089,8000,0.233,0.010]]))

array([17.611])

In [129]:
forecast = tree.predict(x_teste)

In [131]:
forecast.shape

(798,)

In [133]:
with open('forecast.csv', 'w') as forecast:
    
  print(file=forecast)

In [136]:
forecast #se cria um arquivo com as previsões em csv

<_io.TextIOWrapper name='forecast.csv' mode='w' encoding='UTF-8'>

**Random Forest**

In [100]:
from sklearn.ensemble import RandomForestRegressor

In [101]:
rf = RandomForestRegressor(n_estimators=50, criterion='mse')

In [102]:
rf.fit(x_treino, y_treino)

/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_forest.py:400: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,


RandomForestRegressor(criterion='mse', n_estimators=50)

In [103]:
previsoes = rf.predict(x_teste)

In [104]:
rf.score(x_treino,y_treino)

0.9985709266322167

In [105]:
rf.score(x_teste, y_teste)

0.9891992934455102

excelente acurácia

vamos prever resultados

In [107]:
rf.predict(np.array([[13000,0.020,10345,0.060,8000,0.203,0.080]]))

array([17.48652])

In [108]:
rf.predict(np.array([[3000,0.050,10345,0.090,8000,0.103,0.080]]))

array([17.49676])

**Regressão Linear**

In [109]:
from sklearn.linear_model import LinearRegression

In [110]:
rl = LinearRegression()

In [111]:
rl.fit(x_treino, y_treino)

LinearRegression()

In [112]:
pred = rl.predict(x_teste)

In [114]:
pred , y_teste

(array([15.19740959, 15.83204588, 15.2236167 , 15.20111188, 15.20958336,
        14.29656699, 16.37543423, 15.22371828, 15.22182049, 16.7772919 ,
        15.19956826, 14.62258862, 15.2106144 , 15.6003498 , 16.6718275 ,
        14.4669524 , 15.54242647, 15.41829489, 15.20451457, 15.21501817,
        17.16701701, 15.20814342, 15.21482506, 15.21942512, 15.22292003,
        15.20733272, 16.69657058, 13.75052653, 15.20196367, 13.22530363,
        15.44295231, 13.24565467, 16.63546699, 15.21202718, 15.22525515,
        15.15722394, 15.73952813, 16.54773576, 13.40532964, 16.62091729,
        16.02736674, 13.34736367, 13.42415057, 15.19838691, 15.20407526,
        15.22237995, 15.2195352 , 15.085222  , 15.19975807, 15.53023544,
        15.2110195 , 15.16503348, 13.84795538, 13.70183162, 13.28148197,
        15.548951  , 14.6272161 , 16.84756599, 15.22181071, 15.2198628 ,
        14.51037538, 15.21247138, 15.22800169, 16.38809375, 15.23184855,
        15.22618544, 13.76074754, 15.22772829, 15.2

In [116]:
rl.score(x_treino, y_treino)

0.9795279351442409

In [117]:
rl.score(x_teste, y_teste)

0.9753624623660397

excelente acurácia também

vamos prever resultados novamente

In [119]:
rl.predict(np.array([[13000,0.050,10345,0.090,8000,0.103,0.080]]))

array([2749.80145387])