<a href="https://colab.research.google.com/github/bcury/Machine-Learning-Projects/blob/main/ML_Redu%C3%A7%C3%A3o_Dimensionalidade_PCA_LDA__algoritimoRandom_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Preparando a base de dados**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
base_census = pd.read_csv('/content/census.csv')

In [4]:
base_census

age          workclass  ...  native-country  income
0       39          State-gov  ...   United-States   <=50K
1       50   Self-emp-not-inc  ...   United-States   <=50K
2       38            Private  ...   United-States   <=50K
3       53            Private  ...   United-States   <=50K
4       28            Private  ...            Cuba   <=50K
...    ...                ...  ...             ...     ...
32556   27            Private  ...   United-States   <=50K
32557   40            Private  ...   United-States    >50K
32558   58            Private  ...   United-States   <=50K
32559   22            Private  ...   United-States   <=50K
32560   52       Self-emp-inc  ...   United-States    >50K

[32561 rows x 15 columns]

In [5]:
x_census = base_census.iloc[:,0:14].values
y_census = base_census.iloc[:, 14].values

In [6]:
x_census, y_census

(array([[39, ' State-gov', 77516, ..., 0, 40, ' United-States'],
        [50, ' Self-emp-not-inc', 83311, ..., 0, 13, ' United-States'],
        [38, ' Private', 215646, ..., 0, 40, ' United-States'],
        ...,
        [58, ' Private', 151910, ..., 0, 40, ' United-States'],
        [22, ' Private', 201490, ..., 0, 20, ' United-States'],
        [52, ' Self-emp-inc', 287927, ..., 0, 40, ' United-States']],
       dtype=object),
 array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
       dtype=object))

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
label_encoder_workclass = LabelEncoder()
label_encoder_education = LabelEncoder()
label_encoder_marital = LabelEncoder()
label_encoder_occupation = LabelEncoder()
label_encoder_relationship = LabelEncoder()
label_encoder_race = LabelEncoder()
label_encoder_sex = LabelEncoder()
label_encoder_country = LabelEncoder()

In [9]:
x_census[:,1] = label_encoder_workclass.fit_transform(x_census[:,1])
x_census[:,3] = label_encoder_education.fit_transform(x_census[:,3])
x_census[:,5] = label_encoder_marital.fit_transform(x_census[:,5])
x_census[:,6] = label_encoder_occupation.fit_transform(x_census[:,6])
x_census[:,7] = label_encoder_relationship.fit_transform(x_census[:,7])
x_census[:,8] = label_encoder_race.fit_transform(x_census[:,8])
x_census[:,9] = label_encoder_sex.fit_transform(x_census[:,9])
x_census[:,13] =  label_encoder_country.fit_transform(x_census[:,13])


In [10]:
x_census[0]

array([39, 7, 77516, 9, 13, 4, 1, 1, 4, 1, 2174, 0, 40, 39], dtype=object)

In [11]:
from sklearn.preprocessing import StandardScaler
scaler_census = StandardScaler()
x_census = scaler_census.fit_transform(x_census)

In [12]:
x_census

array([[ 0.03067056,  2.15057856, -1.06361075, ..., -0.21665953,
        -0.03542945,  0.29156857],
       [ 0.83710898,  1.46373585, -1.008707  , ..., -0.21665953,
        -2.22215312,  0.29156857],
       [-0.04264203,  0.09005041,  0.2450785 , ..., -0.21665953,
        -0.03542945,  0.29156857],
       ...,
       [ 1.42360965,  0.09005041, -0.35877741, ..., -0.21665953,
        -0.03542945,  0.29156857],
       [-1.21564337,  0.09005041,  0.11095988, ..., -0.21665953,
        -1.65522476,  0.29156857],
       [ 0.98373415,  0.77689313,  0.92989258, ..., -0.21665953,
        -0.03542945,  0.29156857]])

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_census_treino, x_census_teste, y_census_treino, y_census_teste = train_test_split(x_census, y_census, test_size=0.15)

In [15]:
x_census_treino.shape, x_census_teste.shape

((27676, 14), (4885, 14))

**PCA( PRINCIPAL COMPONENT ANALYSIS )**

In [16]:
from sklearn.decomposition import PCA

In [17]:
pca = PCA(n_components=8) #temos 14 mas queremos gerar apenas 8 atributos

In [18]:
x_census_treino_pca = pca.fit_transform(x_census_treino)
x_census_teste_pca = pca.transform(x_census_teste)

In [19]:
x_census_treino_pca.shape

(27676, 8)

In [20]:
x_census_teste_pca.shape

(4885, 8)

esses 8 atributos são baseados em todos os 14 que tinham, então não significa que dos 14 que tinha, foi escolhido apenas 8

In [21]:
pca.explained_variance_ratio_

array([0.15131668, 0.10075015, 0.08948192, 0.07963575, 0.07663087,
       0.07423764, 0.06825088, 0.06667938])

In [22]:
pca.explained_variance_ratio_.sum()

0.7069832700805915

temos a explicção de 70,7% das variaveis

Agora vamos usar o algoritimo de Random Forest

In [23]:
from sklearn.ensemble import RandomForestClassifier

In [24]:
random_forest_census_pca = RandomForestClassifier(n_estimators=40, random_state=0, criterion ='entropy')

In [25]:
random_forest_census_pca.fit(x_census_treino_pca, y_census_treino)

RandomForestClassifier(criterion='entropy', n_estimators=40, random_state=0)

In [26]:
previsao = random_forest_census_pca.predict(x_census_treino_pca)
previsao

array([' <=50K', ' <=50K', ' <=50K', ..., ' >50K', ' <=50K', ' <=50K'],
      dtype=object)

In [27]:
y_census_teste

array([' <=50K', ' <=50K', ' >50K', ..., ' <=50K', ' <=50K', ' <=50K'],
      dtype=object)

In [28]:
from sklearn.metrics import accuracy_score


In [ ]:
accuracy_score(y_census_teste, previsao)

83% de acurácia, mesmo diminuindo com a redução de dimensionalidade, temos uma eficácia melhor que outros algoritimos

PCA serve mais para quando temos uma base de dados com muitos atributos, então ajuda a trabalhar melhor com ela

**Kernel PCA**

Este tópico não roda no espaçço que tenho livre de memoria RAM, mas tem-se uma acurácia de 82% utiliando o mesmo algoritimo de Random Forest

**LDA (Linear Discriminant Analysis)**

In [30]:
#este medtodo necessita da classe, os outros acima, não necessariamente

In [31]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [48]:
lda = LinearDiscriminantAnalysis(n_components=1) #este é o problema do LDA, so podemos trabalhar com redução de dim a 1


In [49]:
x_census_treino_lda = lda.fit_transform(x_census_treino, y_census_treino)
x_census_teste_lda = lda.transform(x_census_teste)

In [50]:
x_census_teste_lda.shape

(4885, 1)

In [52]:
x_census_treino_lda.shape

(27676, 1)

In [54]:
x_census_treino_lda #1 atributo

array([[-1.23139777],
       [ 0.49107817],
       [ 0.47980783],
       ...,
       [-1.00873289],
       [ 0.25685014],
       [-1.53289008]])

In [55]:
from sklearn.ensemble import RandomForestClassifier
random_forest_census_lda = RandomForestClassifier(n_estimators=40, criterion='entropy', random_state=0)

In [56]:
random_forest_census_lda.fit(x_census_treino_lda, y_census_treino)

RandomForestClassifier(criterion='entropy', n_estimators=40, random_state=0)

In [57]:
previsoes = random_forest_census_lda.predict(x_census_treino_lda)
previsoes

array([' <=50K', ' <=50K', ' <=50K', ..., ' >50K', ' <=50K', ' <=50K'],
      dtype=object)

In [58]:
y_census_teste

array([' <=50K', ' <=50K', ' >50K', ..., ' <=50K', ' <=50K', ' <=50K'],
      dtype=object)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_census_teste, previsoes) #resp 0.7334

aqui conseguimos uma acurácia em torno de 73,3%

Não temos muitaas vantagens em usar LDA pois ele é totalmete baseada na classe, e a redução de dim é igual a 1, então a acurácia do modelo cai bastante