<a href="https://colab.research.google.com/github/bcury/Machine-Learning-Projects/blob/main/ML_Unsupervised_Clustering_k_means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

K-Means

In [1]:
pip install plotly --upgrade

     |████████████████████████████████| 25.3 MB 1.6 MB/s 
  Attempting uninstall: plotly
    Found existing installation: plotly 4.4.1
    Uninstalling plotly-4.4.1:
      Successfully uninstalled plotly-4.4.1


In [26]:
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [25]:
from sklearn.cluster import KMeans

In [27]:
x = [20, 27, 21, 37, 46, 53, 55, 47, 52, 32, 39, 41, 39, 48, 48] # base de idades
y = [1000, 1200, 2900, 1850, 900, 950, 2000, 2100, 3000, 5900, 4100, 5100, 7000, 5000, 6500] #base de salarios

In [28]:
grafico = px.scatter(x = x, y = y)
grafico.show()

In [29]:
base_salario = np.array([[20,1000],[27,1200],[21,2900],[37,1850],[46,900],[53,950],[55,2000],[47,2100],[52,3000],[32,5900],[39,4100],[41,5100],[39,7000],[48,5000],[48,6500]])

In [30]:
base_salario  #formato de matriz

array([[  20, 1000],
       [  27, 1200],
       [  21, 2900],
       [  37, 1850],
       [  46,  900],
       [  53,  950],
       [  55, 2000],
       [  47, 2100],
       [  52, 3000],
       [  32, 5900],
       [  39, 4100],
       [  41, 5100],
       [  39, 7000],
       [  48, 5000],
       [  48, 6500]])

In [31]:
#padronização
scaler_salario = StandardScaler()
base_salario = scaler_salario.fit_transform(base_salario)

In [32]:
base_salario #temos que deixar os valores na mesma escala, para o algoritimo nao entender que um atributo é mais importante do que o outro

array([[-1.87963884, -1.11413572],
       [-1.23255006, -1.01725435],
       [-1.78719758, -0.19376273],
       [-0.30813751, -0.70238991],
       [ 0.52383377, -1.1625764 ],
       [ 1.17092255, -1.13835606],
       [ 1.35580506, -0.62972888],
       [ 0.61627503, -0.5812882 ],
       [ 1.0784813 , -0.14532205],
       [-0.77034379,  1.25945777],
       [-0.12325501,  0.38752547],
       [ 0.0616275 ,  0.8719323 ],
       [-0.12325501,  1.79230528],
       [ 0.70871628,  0.82349162],
       [ 0.70871628,  1.55010187]])

In [33]:
#treinamento
Kmeans_salario = KMeans(n_clusters=3)
Kmeans_salario.fit(base_salario)

KMeans(n_clusters=3)

In [44]:
centroides = Kmeans_salario.cluster_centers_ # centroide é a média de todos os elementos dos grupos
centroides #1 centroide para cada um dos clusters

array([[ 0.73953003, -0.72661025],
       [ 0.07703438,  1.11413572],
       [-1.63312883, -0.77505093]])

In [45]:
scaler_salario.inverse_transform(Kmeans_salario.cluster_centers_)  #3grupos

array([[  48.33333333, 1800.        ],
       [  41.16666667, 5600.        ],
       [  22.66666667, 1700.        ]])

In [46]:
rotulos = Kmeans_salario.labels_
rotulos  # 3grupos(de 0 a 2)

array([2, 2, 2, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1], dtype=int32)

In [47]:
novo_grafico = px.scatter(x = base_salario[:,0], y =base_salario[:,1], color = rotulos) # 0 é pra idade e 1 é salario
novo_grafico_2 = px.scatter(x = centroides[:,0], y = centroides[:,1], size = [12,12,12])
novo_grafico_3 = go.Figure(data=novo_grafico.data + novo_grafico_2.data) #combinar graficos
novo_grafico_3.show()  #um centroide para cada grupo

Dados aleatorios agora

In [48]:
from sklearn.datasets import make_blobs # geração de dados aleatorios

In [49]:
x_random, y_random = make_blobs(n_samples=200, centers=5) # centers indica quant clusters quremos

In [51]:
x_random, y_random #y 0 a 4 pois temos 5 clusters 0,1,2,3 e 4

(array([[ -4.20669139,   3.21795611],
        [ -5.12222499,   4.50575167],
        [ -8.91007413,  -6.01458395],
        [ -3.72666874,  -6.69963434],
        [ 10.21960622,   9.45419013],
        [  6.52542523,  -9.84622259],
        [  7.32492783,  -9.65704441],
        [ -2.79203347,   3.47090671],
        [ -4.17900262,   1.28900523],
        [ -2.9238819 ,   2.47979744],
        [ -4.6204466 ,   1.939384  ],
        [ -6.76783736,  -6.25302795],
        [ -3.56070497,   4.12834742],
        [  7.56079276,  -8.78982819],
        [  6.77096667,  -9.69699551],
        [  8.45978158,  -8.90771429],
        [ -6.42361501,  -6.03219109],
        [ -8.48109017,  -4.78133666],
        [ -4.73184745,  -6.5942233 ],
        [  6.38607429,  -9.71188308],
        [ -8.17941526,  -5.01290913],
        [  7.65993959,  -7.04558226],
        [ 10.5762924 ,   8.30941773],
        [  7.25271196,  -8.9507035 ],
        [-10.48475805,  -5.07130095],
        [ 10.73820745,   9.39407518],
        [ -4

In [54]:
graph = px.scatter(x = x_random[:,0], y = x_random[:,1])
graph.show() # sempre aleatorio quando compilamos x_random e y_random

In [55]:
Kmeans_blobs = KMeans(n_clusters=5)
Kmeans_blobs.fit(x_random)


KMeans(n_clusters=5)

In [57]:
rotl = Kmeans_blobs.predict(x_random)
rotl

array([3, 3, 2, 4, 0, 1, 1, 3, 3, 3, 3, 2, 3, 1, 1, 1, 4, 2, 4, 1, 2, 1,
       0, 1, 2, 0, 3, 2, 4, 3, 2, 2, 4, 0, 3, 3, 4, 4, 4, 4, 2, 0, 3, 1,
       2, 0, 2, 4, 3, 0, 4, 4, 2, 3, 2, 0, 2, 1, 4, 0, 4, 1, 3, 1, 4, 2,
       0, 4, 1, 2, 1, 0, 0, 4, 2, 2, 1, 3, 2, 3, 3, 2, 4, 0, 4, 2, 0, 1,
       4, 3, 0, 1, 4, 3, 1, 0, 3, 4, 0, 0, 3, 4, 1, 2, 1, 1, 1, 1, 4, 1,
       1, 4, 2, 2, 0, 4, 0, 4, 0, 1, 1, 0, 2, 1, 2, 4, 3, 0, 3, 4, 2, 1,
       4, 0, 0, 0, 0, 3, 1, 2, 3, 3, 3, 1, 3, 1, 4, 0, 2, 3, 4, 2, 0, 0,
       0, 2, 4, 2, 2, 0, 3, 3, 1, 0, 2, 4, 4, 3, 3, 0, 3, 3, 0, 3, 1, 0,
       1, 0, 1, 4, 1, 4, 4, 2, 0, 1, 2, 4, 1, 2, 0, 2, 2, 3, 3, 2, 0, 4,
       3, 1], dtype=int32)

In [58]:
centroides_ = Kmeans_blobs.cluster_centers_
centroides_

array([[ 9.84359467,  9.22728628],
       [ 7.31118541, -8.53248943],
       [-8.27078545, -5.56858676],
       [-4.0007744 ,  2.81420848],
       [-4.82157984, -5.25154278]])

In [60]:
graph1 = px.scatter(x = x_random[:,0], y = x_random[:,1], color=rotl)
graph2 = px.scatter(x = centroides_[:,0], y = centroides_[:,1], size=(5,5,5,5,5,))
graph_all = go.Figure(data = graph1.data + graph2.data)
graph_all.show()

base real agora  vamos saber se a pessoa vai pagar o cartao de credito baseado no agrupamento dos 6 meses anteriores

In [66]:
base_cartao = pd.read_csv('/content/credit_card_clients.csv', header=1)

In [67]:
base_cartao.head()

ID  LIMIT_BAL  SEX  ...  PAY_AMT5  PAY_AMT6  default payment next month
0   1      20000    2  ...         0         0                           1
1   2     120000    2  ...         0      2000                           1
2   3      90000    2  ...      1000      5000                           0
3   4      50000    2  ...      1069      1000                           0
4   5      50000    1  ...       689       679                           0

[5 rows x 25 columns]

In [68]:
base_cartao.describe()

ID       LIMIT_BAL  ...       PAY_AMT6  default payment next month
count  30000.000000    30000.000000  ...   30000.000000                30000.000000
mean   15000.500000   167484.322667  ...    5215.502567                    0.221200
std     8660.398374   129747.661567  ...   17777.465775                    0.415062
min        1.000000    10000.000000  ...       0.000000                    0.000000
25%     7500.750000    50000.000000  ...     117.750000                    0.000000
50%    15000.500000   140000.000000  ...    1500.000000                    0.000000
75%    22500.250000   240000.000000  ...    4000.000000                    0.000000
max    30000.000000  1000000.000000  ...  528666.000000                    1.000000

[8 rows x 25 columns]

In [69]:
base_cartao['Bill_Total'] = base_cartao['BILL_AMT1'] + base_cartao['BILL_AMT2'] + base_cartao['BILL_AMT3'] + base_cartao['BILL_AMT4'] + base_cartao['BILL_AMT5'] + base_cartao['BILL_AMT6']

In [72]:
base_cartao  # AGORA TEMOS O TOTAL, GRACAS AO AGRUPAMENTO

ID  LIMIT_BAL  SEX  ...  PAY_AMT6  default payment next month  Bill_Total
0          1      20000    2  ...         0                           1        7704
1          2     120000    2  ...      2000                           1       17077
2          3      90000    2  ...      5000                           0      101653
3          4      50000    2  ...      1000                           0      231334
4          5      50000    1  ...       679                           0      109339
...      ...        ...  ...  ...       ...                         ...         ...
29995  29996     220000    1  ...      1000                           0      725349
29996  29997     150000    1  ...         0                           0       21182
29997  29998      30000    1  ...      3100                           1       70496
29998  29999      80000    1  ...      1804                           1      266611
29999  30000      50000    1  ...      1000                           1      230874

[30000 rows x 26 columns]

In [73]:
base_cartao.head()

ID  LIMIT_BAL  SEX  ...  PAY_AMT6  default payment next month  Bill_Total
0   1      20000    2  ...         0                           1        7704
1   2     120000    2  ...      2000                           1       17077
2   3      90000    2  ...      5000                           0      101653
3   4      50000    2  ...      1000                           0      231334
4   5      50000    1  ...       679                           0      109339

[5 rows x 26 columns]

In [77]:
x_cartao = base_cartao.iloc[:, [1, 25]].values
x_cartao  #limite e  #divida dos clientes em matriz

array([[ 20000,   7704],
       [120000,  17077],
       [ 90000, 101653],
       ...,
       [ 30000,  70496],
       [ 80000, 266611],
       [ 50000, 230874]], dtype=int64)

In [78]:
scaler_cartao = StandardScaler()
x_cartao = scaler_cartao.fit_transform(x_cartao)

In [81]:
x_cartao  # algoritimo nao ve nenhum dado com mais importancia agora

array([[-1.13672015, -0.69069198],
       [-0.3659805 , -0.66599747],
       [-0.59720239, -0.44316987],
       ...,
       [-1.05964618, -0.52525745],
       [-0.67427636, -0.00856436],
       [-0.90549825, -0.10271861]])

In [86]:
#aqui nao sabemos o numero de cluster ainda, entao vamos descobrir e depois treinamento

wcss = []
for i in range(1,11): #nao podemos gerar o agrupamento com 0 cluster
  print(i)
  Kmeans_cartao = KMeans(n_clusters=i, random_state=0) #randomstate=0 para sempre termos  o mesmo resultado
  Kmeans_cartao.fit(x_cartao)
  wcss.append(Kmeans_cartao.inertia_)

1
2
3
4
5
6
7
8
9
10


In [88]:
wcss  #10 clusters para decidirmos qual usaremos

[59999.99999999978,
 35196.57080583435,
 20128.132558347686,
 14943.809173865899,
 10707.537016753624,
 8603.395384848965,
 7400.069599689482,
 6353.473303353463,
 5665.823857740179,
 5052.188166408734]

In [90]:
gráfico = px.line(x = range(1,11), y = wcss) # decidir qual cluster sera usado
gráfico.show()

pelo gráfico vimos que 10, 9, 8, 7 e 6 clusters a queda é muito grande de um para outro, já de 5 cluster para 4 já menor, então devemos escolher 4 ou 5 cluster, já os clusters 3, 2 e 1 não quase nenhum mudança de tão pouca diferença.

In [91]:
Kmeans_cartao = KMeans(n_clusters=4, random_state=0)
rotúlos = Kmeans_cartao.fit_predict(x_cartao)

In [92]:
grafics = px.scatter(x = x_cartao[:,0], y = x_cartao[:,1], color=rotúlos)
grafics.show()

eixo x representa limite de cartao de credito(quanto mais pra direita, maior o limite) e y representa os gastos, que represntam o Bill Total

o grupo 0(azul) tem um limite baixo mas tbm gasta pouco, então nao deve ser interessante o banco aumentar o limite desse grupo, ja que nao devem usar.

o grupo 1 (rosa) tem limite de cartao de crédito alto porém não gastam tanto. Nao deve ser interessante pro banco aumentar seus limites, pois ja devem ter um bom limite

o grupo 2(amarelo) é um grupo que gastam mais e nao tem um limite muito alto, deve ser interessante pro banco aumentar o limite para as pessoas de grupo que estão mais no topo no gráfico que gastam mais.

o grupo 3 (vermelho) na parte da direita sao pessoas que tem um limite alto e tbm gastam bastante, deve ser iteressante o banco oferecer mais crédito para essa parte do grupo.

No final, lá em cima temos um OUTLIER, que é a pessoa que mais gasta e que mais tem limite no banco

In [97]:
#aqui podemos descrever esses resultados em uma lista
lista_clientes = np.column_stack((base_cartao , rotúlos))
lista_clientes  # onde vemos os 4 clusters 0 1 2 3 e ja sabemos o que eles representam

array([[     1,  20000,      2, ...,      1,   7704,      0],
       [     2, 120000,      2, ...,      1,  17077,      0],
       [     3,  90000,      2, ...,      0, 101653,      0],
       ...,
       [ 29998,  30000,      1, ...,      1,  70496,      0],
       [ 29999,  80000,      1, ...,      1, 266611,      0],
       [ 30000,  50000,      1, ...,      1, 230874,      0]], dtype=int64)

In [100]:
lista_clientes =  lista_clientes[lista_clientes[:,26].argsort()]
lista_clientes  #deixando alinhado os grupos...veja de 0...... a 3.... ultimo indice

array([[     1,  20000,      2, ...,      1,   7704,      0],
       [ 16789,  30000,      1, ...,      1,  14274,      0],
       [ 16788,  30000,      1, ...,      1,  90453,      0],
       ...,
       [ 20933, 130000,      1, ...,      1, 430686,      3],
       [ 20901, 200000,      1, ...,      0, 864072,      3],
       [ 20270, 150000,      2, ...,      0, 546939,      3]], dtype=int64)

aqui está !!! em um cenário real para o banco, bastaria substituir o primeiro indice pelo nome da pessoa, para assim, o banco aumentar ou não o limite do cartão.

In [101]:
# agora vamos explorar mais...

In [104]:
base_cartao.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month', 'Bill_Total'],
      dtype='object')

In [102]:
x_cartao_mais = base_cartao.iloc[:,[1,2,3,4,5,25]].values

In [103]:
x_cartao_mais

array([[ 20000,      2,      2,      1,     24,   7704],
       [120000,      2,      2,      2,     26,  17077],
       [ 90000,      2,      2,      2,     34, 101653],
       ...,
       [ 30000,      1,      2,      2,     37,  70496],
       [ 80000,      1,      3,      1,     41, 266611],
       [ 50000,      1,      2,      1,     46, 230874]], dtype=int64)

In [107]:
scaler_cartao_mais = StandardScaler()
x_cartao_mais = scaler_cartao_mais.fit_transform(x_cartao_mais)  #padronizar

In [108]:
x_cartao_mais

array([[-1.13672015,  0.81016074,  0.18582826, -1.05729503, -1.24601985,
        -0.69069198],
       [-0.3659805 ,  0.81016074,  0.18582826,  0.85855728, -1.02904717,
        -0.66599747],
       [-0.59720239,  0.81016074,  0.18582826,  0.85855728, -0.16115646,
        -0.44316987],
       ...,
       [-1.05964618, -1.23432296,  0.18582826,  0.85855728,  0.16430256,
        -0.52525745],
       [-0.67427636, -1.23432296,  1.45111372, -1.05729503,  0.59824792,
        -0.00856436],
       [-0.90549825, -1.23432296,  0.18582826, -1.05729503,  1.14067961,
        -0.10271861]])

In [109]:
wcss_ = []
for i in range(1,11): #nao podemos gerar o agrupamento com 0 cluster
  print(i)
  Kmeans_cartao_mais = KMeans(n_clusters=i, random_state=0) #randomstate=0 para sempre termos  o mesmo resultado
  Kmeans_cartao_mais.fit(x_cartao_mais)
  wcss_.append(Kmeans_cartao_mais.inertia_)

1
2
3
4
5
6
7
8
9
10


In [110]:
wcss_

[180000.00000000038,
 143649.08688195905,
 123753.68521018764,
 108637.12912356813,
 95861.32422356469,
 86985.27457788424,
 80306.53189000252,
 76132.86228447758,
 72237.32509871296,
 69020.66723762438]

In [111]:
gráfico_ = px.line(x = range(1,11), y = wcss_) # decidir qual cluster sera usado
gráfico_.show()

In [112]:
Kmeans_cartao_mais = KMeans(n_clusters=4, random_state=0)
rotulos_ = Kmeans_cartao_mais.fit_predict(x_cartao_mais)
rotulos_

array([1, 0, 0, ..., 3, 1, 1], dtype=int32)

In [114]:
# para visualizar o agrupamento feito com mais de 2 itens , temos o PCA( para reduzir dim )

# no fim ficarão só 2 novamente, pois vamos mandar a base completa e teremos o retorno de apenas 2:

from sklearn.decomposition import PCA


In [116]:
pca = PCA(n_components=2)  # 2 é  quantos atributos que queremos chegar
x_cartao_mais_pca = pca.fit_transform(x_cartao_mais) # x_cartao_mais pois possui 6 atributos


In [118]:
x_cartao_mais_pca  #porem aqui só temos 2 atributos!!!

array([[-0.74082054, -1.13671858],
       [-1.48027121, -0.30100547],
       [-0.94737386, -0.48666789],
       ...,
       [-0.79468657, -0.90012663],
       [ 1.17562376, -1.54746987],
       [ 1.13614987, -1.14039836]])

In [120]:
x_cartao_mais_pca.shape # 30.000 registros e 2 atributos

(30000, 2)

In [121]:
grafics2 = px.scatter(x = x_cartao_mais_pca[:,0], y = x_cartao_mais_pca[:,1], color=rotulos_)
grafics2.show()

neste grafico combinamos os atributos!!

In [123]:
lista_clientes_ = np.column_stack((base_cartao, rotulos_))
lista_clientes_ = lista_clientes_[lista_clientes_[:,26].argsort()]
lista_clientes_


array([[ 22235, 250000,      2, ...,      0, 120233,      0],
       [  6902, 300000,      2, ...,      0, 605733,      0],
       [  6903, 180000,      2, ...,      0,  33111,      0],
       ...,
       [  7847,  30000,      1, ...,      1, 168918,      3],
       [  7866,  50000,      1, ...,      0, 132306,      3],
       [ 15000,  50000,      1, ...,      0, 249711,      3]], dtype=int64)

da mesma forma como feito anteriomente!!!!