<a href="https://colab.research.google.com/github/bcury/Machine-Learning-Projects/blob/main/Reiforcement_Learning_Q_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [81]:
import numpy as np
import pandas as pd
import gym
import random

In [82]:
ambiente = gym.make('Taxi-v3').env

In [83]:
ambiente.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



o passageiro poe estar em qualquer um desses pontos: R,G,Y OU B, o quadraro amarelo é o taxi, quando o taxi pegar o passageiro, ele fica verde ; a cor azul(G) é o ponto incicial do passageiro, e a cor roxa(R) é o ponto final do passageiro.

In [84]:
ambiente.reset()
ambiente.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [85]:
print(ambiente.action_space)

Discrete(6)


6 ações possiveis

In [86]:
print(ambiente.observation_space) #4 destinos

Discrete(500)


In [87]:
len(ambiente.P)

500

In [88]:
ambiente.P

{0: {0: [(1.0, 100, -1, False)],
  1: [(1.0, 0, -1, False)],
  2: [(1.0, 20, -1, False)],
  3: [(1.0, 0, -1, False)],
  4: [(1.0, 16, -1, False)],
  5: [(1.0, 0, -10, False)]},
 1: {0: [(1.0, 101, -1, False)],
  1: [(1.0, 1, -1, False)],
  2: [(1.0, 21, -1, False)],
  3: [(1.0, 1, -1, False)],
  4: [(1.0, 17, -1, False)],
  5: [(1.0, 1, -10, False)]},
 2: {0: [(1.0, 102, -1, False)],
  1: [(1.0, 2, -1, False)],
  2: [(1.0, 22, -1, False)],
  3: [(1.0, 2, -1, False)],
  4: [(1.0, 18, -1, False)],
  5: [(1.0, 2, -10, False)]},
 3: {0: [(1.0, 103, -1, False)],
  1: [(1.0, 3, -1, False)],
  2: [(1.0, 23, -1, False)],
  3: [(1.0, 3, -1, False)],
  4: [(1.0, 19, -1, False)],
  5: [(1.0, 3, -10, False)]},
 4: {0: [(1.0, 104, -1, False)],
  1: [(1.0, 4, -1, False)],
  2: [(1.0, 24, -1, False)],
  3: [(1.0, 4, -1, False)],
  4: [(1.0, 4, -10, False)],
  5: [(1.0, 4, -10, False)]},
 5: {0: [(1.0, 105, -1, False)],
  1: [(1.0, 5, -1, False)],
  2: [(1.0, 25, -1, False)],
  3: [(1.0, 5, -1, False)

In [89]:
ambiente.P[484]

{0: [(1.0, 484, -1, False)],
 1: [(1.0, 384, -1, False)],
 2: [(1.0, 484, -1, False)],
 3: [(1.0, 464, -1, False)],
 4: [(1.0, 484, -10, False)],
 5: [(1.0, 484, -10, False)]}

In [90]:
#TREINAMENTO

In [100]:
random.uniform(0,1)

0.45962273855663627

In [101]:
q_table = np.zeros([ambiente.observation_space.n, ambiente.action_space.n])
q_table.shape


(500, 6)

In [102]:
q_table[0]

array([0., 0., 0., 0., 0., 0.])

In [103]:
q_table

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [104]:
np.argmax(np.array([3,5]))

1

In [109]:
#DiFERENÇA tEMPORAL(Q-Learning)
%%time
from IPython.display import clear_output

#hiperparametros
alpha = 0.1 #taxa de aprendizagem
gamma = 0.6 #fator de desconto
epsilon = 0.1

for i in range(1000000):
  estado = ambiente.reset()

  penalidades, recompesa = 0, 0
  done = False
  while not done:
    #exploração
    if random.uniform(0,1) < epsilon:
      acao = ambiente.action_space.sample()
    #exploitation
    else:
      acao = np.argmax(q_table[estado])

    proximo_estado, recompensa, done, info = ambiente.step(acao)

    q_antigo = q_table[estado, acao]
    proximo_maximo = np.max(q_table[proximo_estado])

    q_novo = (1 - alpha) * q_antigo + alpha * (recompensa + gamma * proximo_maximo)
    q_table(estado, acao) = q_novo

    if recompensa == -10:
      penalidades += 1

    estado = proximo_estado

  if i % 100 == 0:
   clear_output(wait=True)
   print('Episodio: ', i)

print('Treinamento concluido')





SyntaxError: ignored

In [111]:
q_table[424]

array([0., 0., 0., 0., 0., 0.])

In [113]:
ambiente.reset()
ambiente.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [114]:
ambiente.encode(2,1,0,3)

223

In [116]:
#Avaliação.... continua.....